# Generated by Django 3.0.5 on 2020-05-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0002_consultation_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='img',
        ),
        migrations.AddField(
            model_name='consultation',
            name='echos',
            field=models.ImageField(blank=True, null=True, upload_to='echo/'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='irms',
            field=models.ImageField(blank=True, null=True, upload_to='irm/'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='radios',
            field=models.ImageField(blank=True, null=True, upload_to='radio/'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tdms',
            field=models.ImageField(blank=True, null=True, upload_to='tdm/'),
        ),
    ]
