# Generated by Django 3.0.5 on 2020-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0003_auto_20200528_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default='/assets/images/default-profile.png', null=True, upload_to=''),
        ),
    ]
