# Generated by Django 3.0.5 on 2020-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0004_auto_20200528_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to=''),
        ),
    ]
