# Generated by Django 3.0.5 on 2020-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0005_auto_20200528_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='echos',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='echo/'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='irms',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='irm/'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='radios',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='radio/'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='tdms',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='tdm/'),
        ),
    ]
