# Generated by Django 3.0.5 on 2020-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0008_auto_20200529_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='descriptionCertificat',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
